[package]
name = "transliterator"
version = "0.0.1"
authors = ["DarkEld3r <stanislav.tkach@gmail.com>"]

[[bin]]
name = "ctransliterator"
path = "cui/main.rs"

[[bin]]
name = "transliterator"
path = "gui/main.rs"

[dependencies.transliterator]
path = "transliterator"
